# NumPy

高水準の数学関数や多次元配列を高速に計算できるライブラリ

In [1]:
import numpy as np

## 配列を作成 np.arange

第一引数以上第二引数未満かつ第三引数の間隔で配列が作成される

In [11]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

## 等間隔の配列を作成 np.linspace

第一引数以上第二引数以下かつ要素の個数が第三引数の等間隔な配列が作成される．

option
> retstep = True 各要素の差分
> endpoint = False 第二引数未満の配列を作成

In [12]:
np.linspace(1, 20, 10, retstep = True)

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
        11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]),
 2.111111111111111)

## ある要素の配列を作成 np.full

（行数，列数）の配列で作成（float）

option
> dtype = int 整数型

In [17]:
np.full((3,4), 0, dtype = int)#要素数，数値

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 行列の次元数　numpy.array.shape

配列(4, 3) (行,列)

In [12]:
arr = np.array([[1, 1, 1],
                [1, 1, 1],
                [1, 1, 1],
                [1, 1, 1]])
print("shape : ", arr.shape, " row : ", arr.shape[0], " column : ", arr.shape[1])

shape :  (4, 3)  row :  4  column :  3


## 配列を比較して最大値,最小値を取得　numpy.maximum / minimum / fmax / fmin

複数の配列の要素を比較して最大値を取得する

maximum minimum : 欠測値をとる

fmax fmin : 欠測値を考慮しない

In [42]:
a1 = np.array([2, 5, 9])
a2 = np.array([5, np.nan, 1])
print(np.maximum(a1, a2), np.minimum(a1, a2))
print(np.fmax(a1, a2), np.fmin(a1, a2))

[ 5. nan  9.] [ 2. nan  1.]
[5. 5. 9.] [2. 5. 1.]


## 配列の要素を四則演算　numpy.add / subtract / multiply / divide

In [45]:
a1 = np.array([4, 8, 9])
a2 = np.array([2, 2, 3])

print("+ : ", np.add(a1, a2))
print("- : ", np.subtract(a1, a2))
print("× : ", np.multiply(a1, a2))
print("÷ : ", np.divide(a1, a2))

+ :  [ 6 10 12]
- :  [2 6 6]
× :  [ 8 16 27]
÷ :  [2. 4. 3.]


## 配列を結合　numpy.concatenate

np.concatenate([結合したいリスト], axis = {0 : 行方向, 1 : 列方向})

In [49]:
a1 = np.array([[4, 8, 9], [4, 8, 9]])
a2 = np.array([[2, 2, 3], [2, 2, 3]])

print(np.concatenate([a1, a2], axis = 0))
print(np.concatenate([a1, a2], axis = 1))

[[4 8 9]
 [4 8 9]
 [2 2 3]
 [2 2 3]]
[[4 8 9 2 2 3]
 [4 8 9 2 2 3]]


## 配列の最大値・最小値を取得する　numpy.max / min / nanmax / nanmin

max min 配列の最大値・最小値を取得/nanmax nanmin欠損値を除く

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
nana = np.array([[1, 2, 3], [4, 5, np.nan]])
print(np.max(a), np.min(a))
print(np.nanmax(nana), np.nanmin(nana))

nan 1
5.0 1.0


## 配列の最大値・最小値のインデックスを取得する　np.argmax / argmin

In [11]:
a = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])

print("配列を一次元：",np.argmax(a), "それぞれの配列ごと（第二引数に１）:", np.argmax(a,1))

配列を一次元： 9 それぞれの配列ごと（第二引数に１）: [4 4]


## 配列の平均を取得する　np.mean / np.nanmean

mean 配列の平均を算出する / nanmean 欠測値を除く

In [6]:
a = np.array([1, 5, 12, 0, 5, 1])
print(np.mean(a))

a2 = np.reshape(a, (2, 3))
print("列の平均", a2, np.mean(a2, axis = 0))
print("行の平均",a2, np.mean(a2, axis = 1))

a3 = np.array([1, 5, 12, 0, 5, np.nan])
print(np.nanmean(a3))

4.0
列の平均 [[ 1  5 12]
 [ 0  5  1]] [0.5 5.  6.5]
行の平均 [[ 1  5 12]
 [ 0  5  1]] [6. 2.]
4.6


## 配列の絶対値を取得する np.abs

In [7]:
a = np.array([-2, 5, -8, -1, -3])
print(np.abs(a))

[2 5 8 1 3]


## 配列の単純平均・加重平均を取得　np.average

In [9]:
a = np.array([1, 5, 12, 0, 5, 1])
print("単純平均", np.average(a))
w = np.array([0.4, 0.2, 0.1, 0.5, 0.2, 0.4])
print("加重平均", np.average(a, weights = w))

単純平均 4.0
加重平均 2.222222222222222


## 配列の形状を変換　np.reshape

配列の次元数を変更する (行, 列, 三次元，...)で指定

In [15]:
a = np.array([1, 5, 12, 0, 5, 1])
print(np.reshape(a, (2, 3)))

[[ 1  5 12]
 [ 0  5  1]]


## 配列のインデックスを指定して値を置換　np.put

put関数の第一引数に配列を指定する．第二引数に変更する値のインデックス，第三引数に置き換え後の値を指定．

In [13]:
a = np.array([1, 5, 12, 0, 5, 1])
np.put(a, 5, 500)
print(a)
b = a
np.put(a, [0, 1, 2], [10, 20, 30])
print(a)

[  1   5  12   0   5 500]
[ 10  20  30   0   5 500]


## 配列の値が条件に一致するか判定　np.all np.any

all

デフォルトでは各要素に0がある場合はFalse,0がない場合はTrueが返される．

axis = 0 : 列方向に判定 axis = 1 : 行方向に判定

判定の条件の指定も可能．

any

いずれかの値が条件に一致する場合はTrue

In [22]:
a = np.array([[1, 7, 1, 3, 1],
              [0, 1, 0, 3, 1],
              [3, 8, 0, 6, 1]])
print(np.all(a))
print(np.all(a, axis = 0))
print(np.all(a, axis = 1))
print(np.all(a > 5))
print(np.all(a < 5, axis = 0))
print(np.any(a < 5))

False
[False  True False  True  True]
[ True False False]
False
[ True False  True False  True]
True


## 条件を指定し配列の値を置換　numpy.putmask

第一引数リスト，第二引数条件，第三引数置換の値

In [5]:
a1 = np.array([1, 5, 2, 6, 8, 3, 4])
np.putmask(a1, a1 >= 5, 100)
print(a1)

[  1 100   2 100 100   3   4]


## 配列の末尾に要素を追加　numpy.append

In [7]:
a1 = np.array([1, 5, 2, 6, 8, 3, 4, 7, 9])
np.append(a1, [9, 20, 4])

array([ 1,  5,  2,  6,  8,  3,  4,  7,  9,  9, 20,  4])

In [11]:
a2 = a1.reshape(3,3)
b = np.array([[1, 2, 3]])
print(a2)
print(np.append(a2, b, axis = 0))#行方向

[[1 5 2]
 [6 8 3]
 [4 7 9]]
[[1 5 2]
 [6 8 3]
 [4 7 9]
 [1 2 3]]
